### ISSUE TITLE
Collecting data

### ISSUE THREAD

**Issue by danielbischofff** [danielbischofff/dataLiteracyPeopleCounting#5]
We decided to collect the data again. 

Monday - Sarthak @Bhardwaj-Sarthak 
Tuesday - Philipp @FreshP-min 
Wednesday - Mihai @mihaifalcusan 
Thursday - Daniel @danielbischofff 
Friday - @FreshP-min  @danielbischofff 

Everbody use the same internet card.

**Comment by PLangsteiner** [comment]
This has been finished for a while
